server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brandaogabriel/ead-config-server-repo
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PERSONAL_ACCESS_TOKEN}

encrypt:
  key: /B?E(H+MbQeThWmZq4t7w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3s6


ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  configServer:
    username: configserver
    password: 'ead123cs'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost